### ISSUE TITLE
Command services in ROS2 Spring Controller plugin

### ISSUE THREAD

**Issue by andermi** [osrf/buoy_sim#44]
Companion to #30.
Spring Controller should accept ROS2 commands via services and communicate commands to Pneumatic Spring plugins

Todo:
~~- [x] `SCPackRateCommand` via `/sc_pack_rate_command`~~
- [x] sc pack rate via parameter
- [x] `ValveCommand` via `/valve_command`
- [x] `PumpCommand` via `/pump_command`
- [ ] `SCResetCommand` via `/sc_reset_command`
- [ ] `BenderCommand` via `/bender_command`
- [ ] `TetherCommand` via `/tether_command`

**Comment by andermi** [comment]
@hamilton8415 Should we call this done? I don't think there's much to model with the Bender (that's the ground fault monitor?), Tether (that just turns on/off the power to the heave cone?), or SC Reset (just reboots the uC?).

**Comment by hamilton8415** [comment]
Yes, The "bender" command is actually in the battery controller, but does turn on and off the ground fault detection as you say.  All we need to model in this environment for the spring controller is "valve", "pump", "sc_packrate".  "Tether" turns on and off the heave cone controller.  We could have the spring controller accept this and have a way to signal the electro-hydraulic PTO plugin (which could represent the added current draw), and the trefoil controller (which would go silent if off).  Or we could have those pieces of code respond to a "tether on/off" command directly.  Just a choice, probably no wrong answer.  A "SC_Reset" command has probably never been issued at sea or testing (that's some damn solid firmware! ;)    Practically, it would just reset the packet sequence number to zero without changing much of anything else  (although it would turn the tether power on as that happens when the controller starts).  I would say it doesn't need to be modeled.

**Comment by andermi** [comment]
closing the rest of these until/if we decide we need them
